version: 0.2

env:
  variables:
    APP_MODULE: "web"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "🔧 설치 시작"
      - chmod +x ./gradlew
      - ./gradlew --version
      - sudo yum install -y postgresql
      - psql --version
      - echo "✅ 설치 완료"

  rds_connection_test:
    commands:
      - echo "📡 RDS PostgreSQL 연결 시도"
      - export PGPASSWORD=$BONGSCO_RDS_PASSWORD
      - psql -h $BONGSCO_RDS_ENDPOINT -U $BONGSCO_RDS_USERNAME -d $BONGSCO_RDS_DB_NAME -p 5432 -c '\q'
      - unset PGPASSWORD
      - echo "✅ RDS PostgreSQL 연결 확인 성공"

  pre_build:
    commands:
      - echo "📁 pre_build 시작"
      - mkdir -p $APP_MODULE/src/main/resources
      - rm -f $APP_MODULE/src/main/resources/application-dev.yml
      - echo $BONGSCO_DEV_APP_YML | base64 --decode > $APP_MODULE/src/main/resources/application-dev.yml
      - echo "✅ pre_build 완료"

  build:
    commands:
      - echo "🛠️ 빌드 시작"
      - ./gradlew :$APP_MODULE:clean :$APP_MODULE:build
      - echo "✅ 빌드 완료"

  post_build:
    commands:
      - echo "🚀 빌드 후 작업 완료"