server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DEV_MOBILE_RDB_URL}
    username: ${DEV_MOBILE_RDB_USERNAME}
    password: ${DEV_MOBILE_RDB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 200
        order_inserts: true
        order_updates: true

sql:
  init:
    mode: always

cors:
  origins: ${DEV_CORS_ALLOWED_ORIGINS}