name: Deploy Mobile Service

on:
  push:
    branches: [ develop ]
    paths:
      - 'mobile/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'mobile/**'

jobs:
  call-reusable-deploy:
    uses: ./.github/workflows/deploy-common.yml
    with:
      app_path: 'mobile'
      container_name: 'mobile-container'
      ecr_repository: 'bongsco/salary-management-backend'
      ecs_service: 'bongsco-mobile-ecs-service'
      ecs_cluster: 'bongsco-salary-management-ecs-cluster'
      codebuild_project_name: 'bongsco-salary-management-dev-cb'
    secrets: inherit
