name: Deploy Web Service Prod

on:
  push:
    branches: [ main ]

jobs:
  call-reusable-deploy:
    uses: ./.github/workflows/deploy-prod-common.yml
    with:
      app_path: 'web'
      container_name: 'web-container'
      ecr_repository: 'bongsco/salary-management-backend'
      ecs_service: 'bongsco-web-service'
      ecs_cluster: 'bongsco-salary-management-ecs-cluster'
    secrets: inherit
